version: 2

models: 
  - name: silver_customers
    columns:
      - name: customer_id
        tests: 
          - unique
          - not_null

  - name: silver_geolocations
    columns:
    - name: geolocation_zip_code_prefix
      tests:
        - not_null
  
  - name: silver_order_payments
    columns:
    - name: order_id
      tests: 
        - not_null
        - unique
  
  - name: silver_orders
    columns:
    - name: order_id
      tests:
        - not_null
        - unique
  
  - name: silver_products
    columns:
    - name: product_id
      tests:
        - not_null
        - unique

  - name: silver_sellers
    columns:
    - name: seller_id
      tests: 
        - not_null
        - unique